Downgrade aws-sdk to the version that vault uses
github.com/aws/aws-sdk-go v1.15.55 is the version vendored in
github.com/hashicorp/vault v1.1.3

This should fix an issue with invalid aws tokens

e.g.

--- FAIL: TestIamAuthClient (5.43s)

panic: Error making API request.

URL: PUT https://127.0.0.1:39715/v1/auth/aws/login

Code: 400. Errors:

* error looking up full ARN of entity &{aws XXXXX assumed-role  go-vault-client-test-role 98d54e23-2886-145b-fe07-7358c5ee96d2}: error creating IAM client: unable to fetch current caller: InvalidClientTokenId: The security token included in the request is invalid

	status code: 403, request id: 66f573d4-0561-11ea-9688-51447e36ea0d [recovered]

	panic: Error making API request.